[tool.ruff]
fix = true
select = [
    "E",
    "W",
    "F",
    "I",
    "N",
    "D",
    "UP",
    "S",
    "B",
    "A",
    "COM818",
    "C4",
    "T100",
    "ISC003",
    "PIE",
    "T20",
    "RET",
    "SIM",
    "PTH",
    "ERA001",
    "PL",
    "FLY002",
    "PERF",
    "RUF001",
    "RUF002",
    "RUF003",
    "RUF005",
    "RUF010",
    "RUF011",
    "RUF015",
    "RUF016",
]
ignore = ["E111", "E114", "E117", "E501", "W191", "W292", "D1", "D203", "D213"]

[tool.ruff.lint.isort]
force-single-line = true
order-by-type = false

[tool.ruff.format]
line-ending = "lf"
